SunOS defines ${CC} to be cc, but doesn't have cc instead (uses gcc).  Have an explicit check for this.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -83,6 +83,29 @@ INSTALL_LIB=
 INSTALL_MAN=
 INSTALL_DATA=
 
+# SunOS sets "cc", but this doesn't exist.
+# It does have gcc, so try that instead.
+# Prefer clang, though.
+
+if [ -z "$(which ${CC} 2>/dev/null)" ]
+then
+	echo "${CC} not found: trying clang" 1>&2
+	echo "${CC} not found: trying clang" 1>&3
+	CC=clang
+	if [ -z "$(which ${CC} 2>/dev/null)" ]
+	then
+		echo "${CC} not found: trying gcc" 1>&2
+		echo "${CC} not found: trying gcc" 1>&3
+		CC=gcc
+		if [ -z "$(which ${CC} 2>/dev/null)" ]
+		then
+			echo "gcc not found: giving up" 1>&2
+			echo "gcc not found: giving up" 1>&3
+			exit 1
+		fi
+	fi
+fi
+
 #----------------------------------------------------------------------
 # Allow certain variables to be overriden on the command line.
 #----------------------------------------------------------------------
